# BUsiness Scenario: Drug Vaccination Trial 
    Vaccination given: 13 to 100 years
    People who are between 13 to 64 years no side effects
    65 and above came across some side affects
    
    MOdel in ANN which has details of peoples with different ages and whether they had side effect or notA
    

In [1]:
import pandas as pd
import numpy as np#input can be provided to Keras library

In [2]:
from random import randint
from sklearn.preprocessing import MinMaxScaler


In [3]:
#Now we will create a dataset
train_sample=[]# Will have list of peoples who have been provided with vaccination or not
train_lablel=[]#Vaccination provide has any side affect or not

for i in range(1000):
    age_young=randint(13,64)
    train_sample.append(age_young)
    train_lablel.append(0)
    
    age_older=randint(65,100)
    train_sample.append(age_older)
    train_lablel.append(1)
    
    
    

In [5]:
print(train_sample,train_lablel)

[24, 82, 39, 95, 44, 81, 60, 80, 64, 81, 31, 73, 43, 75, 64, 75, 21, 74, 30, 91, 13, 77, 30, 83, 53, 87, 33, 96, 20, 86, 14, 76, 33, 92, 44, 79, 45, 95, 27, 67, 60, 69, 20, 92, 54, 78, 48, 96, 38, 76, 45, 70, 61, 89, 26, 78, 32, 85, 61, 96, 60, 98, 49, 69, 25, 77, 32, 98, 38, 94, 39, 81, 27, 75, 42, 66, 54, 71, 36, 84, 39, 71, 20, 67, 63, 71, 60, 95, 24, 96, 53, 68, 15, 87, 47, 90, 60, 97, 58, 73, 28, 77, 56, 89, 46, 91, 43, 76, 54, 90, 61, 73, 36, 86, 54, 95, 39, 89, 58, 66, 27, 100, 31, 95, 39, 82, 52, 75, 48, 65, 29, 75, 44, 85, 63, 93, 31, 66, 57, 66, 52, 79, 16, 66, 29, 72, 61, 73, 25, 65, 54, 82, 44, 77, 41, 90, 33, 67, 14, 74, 44, 96, 45, 77, 58, 90, 60, 82, 57, 79, 62, 69, 46, 97, 48, 84, 44, 65, 63, 84, 55, 65, 61, 84, 23, 72, 35, 76, 45, 73, 38, 94, 32, 90, 27, 78, 51, 100, 63, 74, 22, 72, 23, 99, 51, 68, 50, 76, 30, 91, 46, 98, 34, 75, 24, 74, 55, 99, 52, 81, 38, 72, 14, 90, 60, 67, 33, 79, 26, 73, 61, 66, 19, 94, 40, 84, 14, 67, 16, 74, 43, 72, 18, 78, 21, 99, 33, 84, 38, 8

In [6]:
#As keras expects data in numpy array
train_sample=np.array(train_sample)
train_label=np.array(train_lablel)

In [9]:
print(train_sample)

[24 82 39 ... 83 39 99]


In [8]:
scaler=MinMaxScaler(feature_range=(0,1))#MInmax scalar is used to change the irregular values in train_sample to 0's and 1's
scaler_train=scaler.fit_transform(train_sample)

ValueError: Expected 2D array, got 1D array instead:
array=[24. 82. 39. ... 83. 39. 99.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [10]:
scaler=MinMaxScaler(feature_range=(0,1))#MInmax scalar is used to change the irregular values in train_sample to 0's and 1's
scaler_train=scaler.fit_transform(train_sample.reshape(-1,1))

In [25]:
print(scaler_train)
print(scaler_train.shape)
print(train_label.shape)
print(train_sample.shape)

[[0.12643678]
 [0.79310345]
 [0.29885057]
 ...
 [0.8045977 ]
 [0.29885057]
 [0.98850575]]
(2000, 1)
(2000,)
(2000,)


# Creating ANN model

In [12]:
import keras

Using TensorFlow backend.


In [13]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential#Responsible to create sequence of Ops
from keras.layers import Dense,Activation,Embedding,Flatten,BatchNormalization

from keras.layers import Dropout
from keras.layers import LeakyReLU,ELU,ReLU
from keras.activations import relu,sigmoid
from keras import optimizers

In [31]:
def create_model (layers,activation):
    model=Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=scaler_train.shape[1]))#INput layer
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))#Creating hidden layer with neurons
            model.add(Activation(activation))
            model.add(Dropout(0.3))
            
    model.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))#Output neuron
    model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return model          
        
    

In [32]:
model=KerasClassifier(build_fn=create_model,verbose=0)

In [33]:
layers=[[20],[30,15],[40,35,20]]
activations=['relu','sigmoid']
hyper_param_grid=dict(layers=layers,activation=activations,batch_size=[10],epochs=[12])
grid=GridSearchCV(estimator=model,param_grid=hyper_param_grid,cv=5)
#grid_result=grid.fit(scaler_train,train_label)

In [34]:
grid_result=grid.fit(train_sample,train_label)

W0830 15:37:44.075392 13968 deprecation_wrapper.py:119] From C:\Users\3idiots\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:131: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0830 15:37:44.077064 13968 deprecation_wrapper.py:119] From C:\Users\3idiots\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0830 15:37:44.099008 13968 deprecation.py:506] From C:\Users\3idiots\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0830 15:37:44.261749 13968 deprecation.py:323] From C:\Users\3idiots\Anaconda3\lib\site-packages\tensorflow\python\ops\n

In [35]:
print(grid_result.best_score_,grid_result.best_params_)

0.9729999959468841 {'activation': 'sigmoid', 'batch_size': 10, 'epochs': 12, 'layers': [40, 35, 20]}


In [40]:
#Creating test sample and model
test_sample=[]# Will have list of peoples who have been provided with vaccination or not
test_lablel=[]#Vaccination provide has any side affect or not

for i in range(400):
    age_young=randint(13,64)
    test_sample.append(age_young)
    test_lablel.append(0)
    
    age_older=randint(65,100)
    test_sample.append(age_older)
    test_lablel.append(1)
    
test_sample=np.array(test_sample)
test_label=np.array(test_lablel)

In [39]:
model.predict_classess(test_sample,test_label)

AttributeError: 'KerasClassifier' object has no attribute 'predict_classess'

In [41]:
test_sample


array([ 34,  90,  63,  79,  58,  78,  46,  82,  16, 100,  17,  81,  64,
        84,  48,  97,  47,  79,  64,  71,  14,  93,  60,  81,  17,  72,
        53,  68,  31,  88,  54,  83,  16,  89,  51,  93,  35,  82,  55,
        76,  50,  96,  54,  65,  18,  89,  43,  88,  29,  66,  37,  94,
        26,  95,  47,  69,  57,  74,  39,  65,  20,  87,  60,  96,  24,
        67,  41,  93,  26,  90,  43,  79,  29,  80,  59,  67,  40,  77,
        35,  74,  33,  79,  55,  75,  40,  73,  45,  73,  29,  79,  31,
        90,  35, 100,  32,  91,  17,  73,  48,  88,  55,  73,  55,  92,
        36,  93,  37,  76,  62,  87,  49,  92,  16,  92,  14,  79,  60,
        82,  29,  72,  54,  88,  20,  79,  31,  93,  45,  69,  33,  76,
        30,  77,  23,  89,  35,  84,  59,  69,  56,  85,  25,  85,  50,
        65,  64,  72,  26,  73,  57,  84,  18,  89,  15,  88,  57,  98,
        50,  86,  51,  82,  47,  74,  21,  91,  42,  78,  20,  96,  20,
        68,  36,  93,  53,  72,  38,  65,  37,  85,  34,  98,  3

In [42]:
y_pred=grid.predict(test_sample)
y_pred=(y_pred>0.5)
print(y_pred)

[[False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 

In [43]:
#Checking through Confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,test_label)

In [44]:
cm

array([[400,  14],
       [  0, 386]], dtype=int64)

In [46]:
#To check the accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(test_label,y_pred)
print('The accuracy is',accuracy)

The accuracy is 0.9825
